# Site settings

title: Phase Field Models of Ternary Eutectoid Alloys
header-img: img/home-bg.png
email: aiskakov3@gatech.edu
description: "Process-Structure Linkage of Ternary Eutectoid Al Alloy"
baseurl: "/s2k_drive_lounge"
url: "http://aiskakov.github.io"
github_username: aiskakov
project_repository: s2k_drive_logue

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
